"""Report Agent - Terminating tool for generating comprehensive research reports."""
from typing import Dict, Any, List, Optional
from datetime import datetime


class ReportAgent:
    """
    Report Agent that serves as a terminating tool for both main agent and subagents.
    Generates comprehensive markdown reports from research findings.
    """
    
    def __init__(self):
        """Initialize the Report Agent."""
        pass
    
    def generate_subagent_report(
        self,
        subtopic: str,
        instructions: str,
        findings: Dict[str, Any],
        agent_id: str
    ) -> str:
        """
        Generate a report for a single subagent's research.
        
        Args:
            subtopic: The subtopic researched
            instructions: Original research instructions
            findings: Research findings dictionary
            agent_id: Subagent identifier
            
        Returns:
            Complete markdown report for this subagent
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        completed = findings.get("completed", False)
        
        sections = []
        
        # Header
        sections.append(f"# Subagent Research Report: {subtopic}")
        sections.append(f"\n**Agent ID:** {agent_id}")
        sections.append(f"**Generated:** {timestamp}")
        sections.append(f"**Status:** {'Complete' if completed else 'Incomplete'}\n")
        
        # Instructions
        sections.append("---\n")
        sections.append("## Research Instructions\n")
        sections.append(instructions)
        sections.append("\n")
        
        # Search Queries
        search_queries = findings.get("search_queries", [])
        if search_queries:
            sections.append("---\n")
            sections.append("## Search Queries\n")
            sections.append(f"**Total Queries:** {len(search_queries)}\n")
            for i, query in enumerate(search_queries, 1):
                sections.append(f"{i}. {query}")
            sections.append("\n")
        
        # Key Findings
        agent_findings = findings.get("findings", [])
        if agent_findings:
            sections.append("---\n")
            sections.append("## Key Findings\n")
            for i, finding in enumerate(agent_findings, 1):
                query = finding.get("query", "")
                result = finding.get("result", "")
                sections.append(f"### Finding {i}\n")
                sections.append(f"**Query:** {query}\n")
                sections.append(f"**Results:**\n{result}\n")
        
        # Conclusion
        sections.append("---\n")
        sections.append("## Conclusion\n")
        if completed:
            sections.append(f"This subagent has completed research on: **{subtopic}**")
        else:
            sections.append(f"This subagent's research on **{subtopic}** was interrupted or incomplete.")
        
        sections.append("\n---\n")
        sections.append(f"*Report generated by Report Agent*\n")
        
        return "\n".join(sections)
    
    def generate_main_report(
        self,
        title: str,
        subagent_reports: List[str],
        main_agent_analysis: Optional[str] = None,
        topic: Optional[str] = None
    ) -> str:
        """
        Generate a comprehensive main report combining all subagent findings.
        
        Args:
            title: Report title
            subagent_reports: List of subagent report strings
            main_agent_analysis: Optional main agent synthesis/analysis
            topic: Research topic
            
        Returns:
            Complete consolidated markdown report
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        num_subagents = len(subagent_reports)
        
        sections = []
        
        # Title and metadata
        sections.append(f"# {title}")
        sections.append(f"\n**Generated:** {timestamp}")
        sections.append(f"**Research Agents:** {num_subagents} subagents")
        if topic:
            sections.append(f"**Topic:** {topic}")
        sections.append("\n")
        
        # Executive Summary
        sections.append("---\n")
        sections.append("## Executive Summary\n")
        sections.append("This report presents comprehensive research findings from a multi-agent research system.")
        sections.append("Multiple specialized subagents conducted independent research on assigned subtopics,")
        sections.append("ensuring thorough coverage while maintaining context isolation.\n")
        
        # Table of Contents
        sections.append("---\n")
        sections.append("## Table of Contents\n")
        for i, report in enumerate(subagent_reports, 1):
            # Extract subtopic from report title
            lines = report.split("\n")
            for line in lines:
                if line.startswith("# Subagent Research Report:"):
                    subtopic = line.replace("# Subagent Research Report:", "").strip()
                    sections.append(f"{i}. [{subtopic}](#subagent-{i}-{subtopic.lower().replace(' ', '-')})")
                    break
        
        if main_agent_analysis:
            sections.append(f"{num_subagents + 1}. [Main Agent Analysis & Synthesis](#main-agent-analysis--synthesis)")
        
        sections.append(f"{num_subagents + 2}. [Overall Conclusion](#overall-conclusion)\n")
        
        # Subagent Reports
        sections.append("---\n")
        sections.append("## Subagent Research Reports\n")
        
        for i, report in enumerate(subagent_reports, 1):
            # Modify report to include section anchor
            sections.append(f"\n### Subagent {i}\n")
            sections.append(report)
            sections.append("\n")
        
        # Main Agent Analysis
        if main_agent_analysis:
            sections.append("---\n")
            sections.append("## Main Agent Analysis & Synthesis\n")
            sections.append(main_agent_analysis)
            sections.append("\n")
        
        # Overall Conclusion
        sections.append("---\n")
        sections.append("## Overall Conclusion\n")
        sections.append("This research was conducted by a sophisticated multi-agent system with specialized subagents.")
        sections.append("Each subagent focused on specific aspects of the research topic,")
        sections.append("ensuring comprehensive coverage while maintaining context isolation.")
        sections.append("The findings have been synthesized to provide a complete understanding of the topic.\n")
        
        sections.append("---\n")
        sections.append(f"*Report generated by Multi-Agent Research System*\n")
        
        return "\n".join(sections)
    
    def generate_failure_report(
        self,
        subtopic: str,
        agent_id: str,
        error_message: str
    ) -> str:
        """
        Generate a failure report when a subagent encounters an error.
        
        Args:
            subtopic: The subtopic that failed
            agent_id: Subagent identifier
            error_message: Error description
            
        Returns:
            Failure report in markdown format
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        sections = [
            f"# Subagent Research Failure Report: {subtopic}",
            f"\n**Agent ID:** {agent_id}",
            f"**Generated:** {timestamp}",
            f"**Status:** FAILED\n",
            "---\n",
            "## Error Details\n",
            f"The subagent encountered an error while researching: **{subtopic}**\n",
            "### Error Message\n",
            f"```\n{error_message}\n```\n",
            "---\n",
            "## Recommendation\n",
            "This subagent's research could not be completed. Consider reassigning this subtopic to a new subagent.",
            "\n---\n",
            "*Failure report generated by Report Agent*\n"
        ]
        
        return "\n".join(sections)
