"""Report generation tool for creating final markdown reports."""
from typing import Dict, Any, List, Optional
from datetime import datetime
from src.workspace.manager import WorkspaceManager


class ReportTool:
    """
    Tool for generating comprehensive markdown reports.
    This is a terminating tool that finalizes the research process.
    """
    
    def __init__(self, workspace_manager: WorkspaceManager):
        self.workspace = workspace_manager
    
    def generate_report(
        self,
        title: str,
        subagent_results: Dict[str, str],
        main_agent_analysis: Optional[str] = None,
        output_filename: Optional[str] = None
    ) -> str:
        """
        Generate a comprehensive markdown report.
        
        Args:
            title: Report title
            subagent_results: Dictionary of subagent names to their findings
            main_agent_analysis: Optional main agent synthesis/analysis
            output_filename: Optional filename to save the report
            
        Returns:
            Generated markdown report
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Build report sections
        sections = []
        
        # Title and metadata
        sections.append(f"# {title}")
        sections.append(f"\n**Generated:** {timestamp}")
        sections.append(f"**Research Agents:** {len(subagent_results)} subagents\n")
        
        # Executive Summary
        sections.append("---\n")
        sections.append("## Executive Summary")
        sections.append("\nThis report presents research findings from a multi-agent research system.")
        sections.append("Multiple subagents conducted independent research on assigned subtopics,")
        sections.append("and their findings have been synthesized below.\n")
        
        # Table of Contents
        sections.append("---\n")
        sections.append("## Table of Contents")
        for i, (agent_name, _) in enumerate(subagent_results.items(), 1):
            section_title = agent_name.replace("_", " ").title()
            sections.append(f"{i}. [{section_title}](#{agent_name}-research)")
        if main_agent_analysis:
            sections.append(f"{len(subagent_results) + 1}. [Synthesis & Analysis](#synthesis--analysis)")
        sections.append(f"{len(subagent_results) + 2}. [Conclusion](#conclusion)\n")
        
        # Subagent Research Sections
        sections.append("---\n")
        for agent_name, findings in subagent_results.items():
            section_title = agent_name.replace("_", " ").title()
            sections.append(f"## {section_title} Research\n")
            sections.append(f"### Agent: {agent_name}\n")
            sections.append(findings)
            sections.append("\n---\n")
        
        # Main Agent Synthesis
        if main_agent_analysis:
            sections.append("## Synthesis & Analysis\n")
            sections.append(main_agent_analysis)
            sections.append("\n---\n")
        
        # Conclusion
        sections.append("## Conclusion\n")
        sections.append("This research was conducted by a multi-agent system with specialized subagents.")
        sections.append("Each subagent focused on specific aspects of the research topic,")
        sections.append("ensuring comprehensive coverage while maintaining context isolation.")
        sections.append("\n---\n")
        sections.append(f"*Report generated by Multi-Agent Research System*")
        
        # Combine all sections
        report = "\n".join(sections)
        
        # Save to file if filename provided
        if output_filename:
            self.workspace.write_file("main", output_filename, report)
        
        return report
    
    def generate_summary_report(
        self,
        title: str,
        subagent_results: Dict[str, str]
    ) -> str:
        """
        Generate a concise summary report.
        
        Args:
            title: Report title
            subagent_results: Dictionary of subagent findings
            
        Returns:
            Concise summary markdown
        """
        timestamp = datetime.now().strftime("%Y-%m-%d")
        
        sections = [
            f"# {title}",
            f"\n**Date:** {timestamp}\n",
            "---\n",
            "## Key Findings\n"
        ]
        
        for agent_name, findings in subagent_results.items():
            # Extract first paragraph as key finding
            first_para = findings.split("\n\n")[0][:200] + "..." if len(findings.split("\n\n")[0]) > 200 else findings.split("\n\n")[0]
            sections.append(f"**{agent_name}:** {first_para}\n")
        
        sections.append("---\n")
        sections.append("*Summary generated by Multi-Agent Research System*")
        
        return "\n".join(sections)
    
    def compare_reports(
        self,
        title: str,
        reports: Dict[str, str]
    ) -> str:
        """
        Generate a comparative report from multiple research sessions.
        
        Args:
            title: Report title
            reports: Dictionary of session names to report content
            
        Returns:
            Comparative analysis report
        """
        sections = [
            f"# {title}",
            f"\n**Comparison of {len(reports)} Research Sessions**\n",
            "---\n",
            "## Overview\n"
        ]
        
        for session_name, content in reports.items():
            sections.append(f"### {session_name}\n")
            # Extract key sections
            if "## Executive Summary" in content:
                exec_start = content.find("## Executive Summary")
                exec_end = content.find("\n---", exec_start)
                if exec_end == -1:
                    exec_end = exec_start + 500
                sections.append(content[exec_start:exec_end])
            sections.append("\n")
        
        sections.append("---\n")
        sections.append("*Comparative report generated by Multi-Agent Research System*")
        
        return "\n".join(sections)
